// @ts-ignore
/* eslint-disable */

/**
 * This file is automatically generated by the @umijs/openapi plugin. Please do not modify it at will. If you need to modify it, please customize it by configuring openapi.config.ts.
 * */

import { request, type RequestOptions } from '@/utils/request';

/** Login POST /api/auth/login */
export async function authLogin(body: any, options?: RequestOptions) {
  return request<API.ResOp>('auth/api/permission/user/login', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    data: body,
    ...(options || {}),
  });
}

/** Register POST /api/auth/register */
export async function authRegister(
  body: any,
  options?: RequestOptions
) {
  return request<any>('/api/auth/register', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    data: body,
    ...(options || {}),
  });
}

export async function authGenerateOtp(
  body: any,
  options?: RequestOptions
) {
  return request<any>('auth/api/permission/user/generate-otp-email', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    data: body,
    ...(options || {}),
  });
}

export async function authConfirmOtp(
  body: any,
  options?: RequestOptions
) {
  return request<any>('auth/api/permission/user/confirm-otp-email', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    data: body,
    ...(options || {}),
  });
}

export async function authForgetPassword(
  body: any,
  options?: RequestOptions
) {
  return request<any>('auth/api/permission/user/forget-password-email', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    data: body,
    ...(options || {}),
  });
}

export async function authResetPassword(
  body: any,
  options?: RequestOptions
) {
  return request<any>('auth/api/permission/user/reset-password', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    data: body,
    ...(options || {}),
  });
}