name: jobhub-fe

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd /home/ITJOB
          git fetch origin
          git checkout develop
          git pull
          npm install
          npm run build
          pm2 reload jobhub-fe
          sudo systemctl reload nginx
